package com.bharathvishal.textfileviewer.Constants

/**
 *
 * Constants
 *
 */
object Constants {
    const val SYMBOL_HYPHEN = "-"
    const val STRING_EMPTY = " "
    const val FILE_PATH_TYPE_URI = "FILE_PATH_TYPE_URI"

    const val FILE_PATH_URI_FROM_BUNDLE = "FILE_PATH_URI_FROM_BUNDLE"
    const val FILE_PATH_FILE_FROM_BUNDLE = "FILE_PATH_FILE_FROM_BUNDLE"
    const val FILE_SHOULD_SHOW_LINE_NUMBER = "FILE_SHOULD_SHOW_LINE_NUMBER"
    const val FILE_SHOULD_SHOW_LINE_LENGTH = "FILE_SHOULD_SHOW_LINE_LENGTH"

    const val SHOULD_OPEN_TEXT_FILE_SELECTOR = "SHOULD_OPEN_TEXT_FILE_SELECTOR"

    const val SAVED_INSTANCE_SHOW_LINE_NUMBER_SETTING = "SAVED_INSTANCE_SHOW_LINE_NUMBER_SETTING"
    const val SAVED_INSTANCE_SHOW_LINE_LENGTH_SETTING = "SAVED_INSTANCE_SHOW_LINE_LENGTH_SETTING"
    const val SAVED_INSTANCE_FILE_URI_LOCATION = "SAVED_INSTANCE_FILE_URI_LOCATION"
    const val SAVED_INSTANCE_FILE_PATH_LOCATION = "SAVED_INSTANCE_FILE_PATH_LOCATION"
    const val SAVED_INSTANCE_FILE_NAME = "SAVED_INSTANCE_FILE_NAME"
    const val SAVED_INSTANCE_SCROLL_RC_SETTING ="SAVED_INSTANCE_SCROLL_RC_SETTING"
}